<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9761" started-at="2018-03-10T02:45:25Z" finished-at="2018-03-10T02:45:34Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9761" started-at="2018-03-10T02:45:25Z" finished-at="2018-03-10T02:45:34Z">
      <class name="selenium.HRMLoginReTesting">
        <test-method status="PASS" signature="start()[pri:0, instance:selenium.HRMLoginReTesting@536aaa8d]" name="start" is-config="true" duration-ms="6692" started-at="2018-03-10T02:45:25Z" finished-at="2018-03-10T02:45:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="FAIL" signature="logic()[pri:0, instance:selenium.HRMLoginReTesting@536aaa8d]" name="logic" duration-ms="6" started-at="2018-03-10T02:45:31Z" finished-at="2018-03-10T02:45:31Z">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[C:\Users\PHANITHEJ\Downloads\Workspace 12\TestData\OrangeHRmLogin.xls (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: C:\Users\PHANITHEJ\Downloads\Workspace 12\TestData\OrangeHRmLogin.xls (The system cannot find the path specified)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at selenium.HRMLoginReTesting.logic(HRMLoginReTesting.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logic -->
        <test-method status="PASS" signature="end()[pri:0, instance:selenium.HRMLoginReTesting@536aaa8d]" name="end" is-config="true" duration-ms="3042" started-at="2018-03-10T02:45:31Z" finished-at="2018-03-10T02:45:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- selenium.HRMLoginReTesting -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
